name: tiago_simulationsimulation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pip
  - pip:
      - py_trees
      - webots
